### ISSUE TITLE
Buildings won't purchase

### ISSUE THREAD

**Issue by vandiere** [cameroncondry/cbc-kitten-scientists#195]
Just updated to the latest release but now, regardless of resource count, KS won't purchase any buildings.  I have the trigger set to default.  Crafting still works.   I did have to delete and then re-install the script for the most recent update to work with 1.4.0.6.  Using Chrome and TamperM.

**Comment by andrealessi** [comment]
This also appears to be an issue with trading:

`Uncaught TypeError: button.tradeMultiple is not a function
    at TradeManager.trade (eval at <anonymous> (:1:1), <anonymous>:818:20)
    at Engine.trade (eval at <anonymous> (:1:1), <anonymous>:546:30)
    at Engine.iterate (eval at <anonymous> (:1:1), <anonymous>:395:50)`

**Comment by tsaulic** [comment]
same thing with hunting

`kitten-scientists.user.js:770 Uncaught TypeError: button.tradeMultiple is not a function
    at TradeManager.trade (kitten-scientists.user.js:770)
    at Engine.trade (kitten-scientists.user.js:498)
    at Engine.iterate (kitten-scientists.user.js:347)`

**Comment by TeWeBu** [comment]
#200 resolves this issue

**Comment by predakanga** [comment]
@TeWeBu #200 does resolve the building issue, but not the trading issue

**Comment by TeWeBu** [comment]
@predakanga Ups. You are right. I did half the job. :-(

**Comment by predakanga** [comment]
I think they're different issues, to be fair - but your PR definitely fixes the building issue

**Comment by TeWeBu** [comment]
#201 should fix the trading issue.

**Comment by predakanga** [comment]
Nice work :)
